[package]
name = "bevy-behaviour-tree-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.3"
disjoint_impls = "0.3.0"
